### ISSUE TITLE
Implement Plugin Channels

### ISSUE THREAD

**Issue by HurricanKai** [SharpenedMinecraft/SM2#255]
**Desired behaviour**
Ability to use Plugin Channels

**Related Issues*
- [ ] Login Plugin Request #115
- [ ] Login Plugin Response #113 
- [ ] Plugin Message (clientbound) #144 
- [ ] Plugin Message (serverbound) #215

See https://wiki.vg/Plugin_channels
